### ISSUE TITLE
Add (yellow) red cards

### ISSUE THREAD

**Issue by maxbiostat** [IgorMichels/BrazilianSoccerData#1]
Add information on whether a red card has occurred and how many yellow cards were handed out in each sub-game

**Comment by IgorMichels** [comment]
- [x] Create parser to catch red (yellow) cards
- [x] Process player whom receive that card
- [x] Save information in `games.json`
- [x] Save information in `squads.json`
    - [x] Red card
    - [x] Yellow card
- [x] Update README with new `json` format
